name: plugin-swift-hello
version: 1.0.0
description: "A simple Swift plugin that provides greeting functionality"
author: "ARO Team"
license: MIT
aro-version: ">=0.1.0"

source:
  git: "git@github.com:arolang/plugin-swift-hello.git"
  ref: "main"

provides:
  - type: swift-plugin
    path: Sources/

  - type: aro-files
    path: features/

build:
  swift:
    minimum-version: "6.2"
    targets:
      - name: HelloPlugin
        path: Sources/
